Create wrangle.py
osome-iu/osometweet pull request #76
Opened 2021-07-28 22:48 UTC by mr-devs

Addressing #70, this PR creates some data wrangling functions that I thought could be helpful. 

_Note_: I have not been able to actually run the `tests.py` script because I am maxed out on my monthly tweets so it will fail no matter what. Please look that script over carefully or give it a go on your end. Either way, it shouldn't break anything old because it's a separate module.

I was originally intending to create functions like `wrangle.extract(tweet_obj, "hashtags")` - which would take a tweet object and return all the hashtags - but this seems too specific given Twitter's new data format. I ended up going with a handful of general functions that I felt could be applicable/useful for any bit of Twitter data (I think?).

Of course, please share your thoughts on whether these are worth including or not.

2021-07-29 16:50 UTC, mr-devs commented
FYI, I will update the Wiki with examples that utilize actual tweet data after this is merged.

2021-08-09 22:47 UTC, yangkcatiu reviewed
BTW, you can use

```sh
python tests.py TestWranlge
```
To just run the test you need

2021-08-09 22:47 UTC, yangkcatiu commented on osometweet/wrangle.py
> +        new_key = parent_key + sep + k if parent_key else k
```py
new_key = f"{parent_key}{sep}{k}" if parent_key else k
```
Probably safer this way since `parent_key` and `k` might not be str.

2021-08-09 22:47 UTC, yangkcatiu commented on osometweet/wrangle.py
> +    if not isinstance(dictionary,dict):
```py
if not isinstance(dictionary, dict):
```
Just a format thing

2021-08-09 22:47 UTC, yangkcatiu commented on osometweet/wrangle.py
> +    if not isinstance(path,list):
```py
if not isinstance(path, list):
```
Just a format thing

2021-08-09 23:04 UTC, yangkcatiu requested changes

2021-08-09 23:04 UTC, yangkcatiu commented on osometweet/wrangle.py
> +def get_dict_paths(dictionary: dict, path: list=[]):
I added a default value to `path` to make the tests run. But this is not the ideal solution, see https://docs.python-guide.org/writing/gotchas/

2021-08-09 23:04 UTC, yangkcatiu commented on osometweet/wrangle.py
> +def get_dict_val(dictionary:dict, key_list:list=[]):
Same here.

2021-08-09 23:04 UTC, yangkcatiu commented on osometweet/wrangle.py
> +        if not hasattr(retval, '__iter__'):
We might encounter the corner cases where retval is a string or a list, which will break the code.

I added a test case for this. The test case fails if you run it now.

2021-08-10 13:56 UTC, mr-devs commented on osometweet/wrangle.py
> +def get_dict_paths(dictionary: dict, path: list=[]):
Thanks!

Do you think that this is an issue for this function? It doesn't seem to display the "gotcha" that is described in the linked-to article but maybe I'm missing something?

2021-08-10 13:57 UTC, mr-devs commented on osometweet/wrangle.py
> +        if not hasattr(retval, '__iter__'):
I made a change that I think deals with this - just made this line more specific. However, now I'm not sure if it breaks something else... 😅  This function always confuses me haha

2021-08-10 14:01 UTC, mr-devs commented
Thanks for the great feedback @yangkcatiu. Check out line 218 from my latest commit and let me know if you think this solves the issue with the `get_dict_val` edge case that you highlighted. It now passes the tests but not sure if it breaks something else?

I also made some minor formatting changes after running pylint.

2021-08-11 04:07 UTC, yangkcatiu commented on osometweet/wrangle.py
> +def get_dict_paths(dictionary: dict, path: list=[]):
Not sure if this is going to cause some problems. Let's keep it as it is for now.

2021-08-11 04:11 UTC, yangkcatiu commented on osometweet/wrangle.py
> +        if not hasattr(retval, '__iter__'):
Should be good now.

2021-08-11 04:11 UTC, yangkcatiu approved these changes

2021-08-11 04:14 UTC, yangkcatiu commented
Let's come back to this If we see new bugs in the future. I don't have any cases that would break the code for now.

2021-08-11 04:14 UTC, merged